### ISSUE TITLE
Баг в навигации

### ISSUE THREAD

**Issue by andykarpov** [EvgeniyRU/ZX_FDD_Emulator#1]
Обнаружилась интересная бага: при перемещении по списку файлов с помощью энкодера (возможно такая же бага будет и с кнопками), когда доходишь до последнего файла в списке и пытаешься переместиться дальше (естественно, никуда не перемещаемся, курсор визуально остается на последнем файле), а потом возвращаешься назад, то вся логика зависает на последних двух файлах (можно перемещаться только по ним), то есть переместить курсор назад не представляется возможным. Предполагаю, где-то есть нестыковки в вычислении f_index / disp_index / first.

**Comment by andykarpov** [comment]
Как минимум нашлось пару мест с такой ошибкой:
readdir() возвращает int8_t, 
но при этом в коде используется uint8_t res = readdir(...);
и потом результат сравнивается с "-1".

**Comment by andykarpov** [comment]
заменил uint8_t на int8_t, результат readdir() сравниваю не только с -1, но и с -2, вроде бы заработало как надо: https://github.com/andykarpov/ZX_FDD_Emulator/blob/master/ZX_FDD_Emulator.ino

**Comment by EvgeniyRU** [comment]
Спасибо, всё поправил!
